### ISSUE TITLE
Issue with Multi-Mutant Sequence Handling

### ISSUE THREAD

**Issue by aaaaaaaaa21-code** [idmjky/EvolvePro#5]
Hi, I've been exploring your published model and find it very interesting. I attempted to run it with my data but encountered an error. 

In my case, I'm working with sequences that contain multiple amino acid mutations. I changed the single_mutant flag in the read_experimental_data function within top_layer.py to false. This modification led to the following error:

Embeddings and labels are aligned
Traceback (most recent call last):
  File "/media/dell/newdisk/EvolvePro-main/top_layer.py", line 355, in <module>
    df_test, df_all = top_layer(
  File "/media/dell/newdisk/EvolvePro-main/top_layer.py", line 205, in top_layer
    y_pred_test = model.predict(X_test)
  File "/home/dell/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_forest.py", line 1064, in predict
    X = self._validate_X_predict(X)
  File "/home/dell/anaconda3/lib/python3.9/site-packages/sklearn/ensemble/_forest.py", line 641, in _validate_X_predict
    X = self._validate_data(
  File "/home/dell/anaconda3/lib/python3.9/site-packages/sklearn/base.py", line 633, in _validate_data
    out = check_array(X, input_name="X", **check_params)
  File "/home/dell/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py", line 1026, in check_array
    raise ValueError(
ValueError: Found array with 0 sample(s) (shape=(0, 1280)) while a minimum of 1 is required by RandomForestRegressor.

When I do not modify single_mutant to false, all the output results are 1. Could you help me resolve this issue?

Thank you for your assistance.

**Comment by idmjky** [comment]
Hi, Can you attach your input result csv file, so I can check the format. Also, is that aligned with the name column in your embedding files? if you can attach these two, then I can help debug this.

**Comment by aaaaaaaaa21-code** [comment]
> Hi, Can you attach your input result csv file, so I can check the format. Also, is that aligned with the name column in your embedding files? if you can attach these two, then I can help debug this.

Thank you for your response and reminder. I realized the error was due to not inputting the sequence needed for prediction, resulting in the absence of X_test. I have now resolved this issue and successfully run the model!

**Comment by Bartillery** [comment]
I would like to know the specific format of the file, as I want to input experimental data for multiple mutation sequences into the model. In your example, only the format for single mutations is provided:

Variant    fitness
WT         1
24K        0.318481518
47A        0.206254044
Could you please provide the format for multiple mutations as well?

**Comment by idmjky** [comment]
You can write your own way to parse multimutant during the embedding generation stage. The easiest way is to use a format like G47A_E643G.

-------------
Kaiyi Jiang
Ph.D. Candidate, MIT Biological Engineering
AbuGoot Lab, Cambridge, MA, 02139
Email: ***@***.******@***.***>
https://idmjky.github.io/

From: Bartillery ***@***.***>
Date: Monday, January 6, 2025 at 4:58 AM
To: idmjky/EvolvePro ***@***.***>
Cc: kaaiyii ***@***.***>, Comment ***@***.***>
Subject: Re: [idmjky/EvolvePro] Issue with Multi-Mutant Sequence Handling (Issue #5)

I would like to know the specific format of the file, as I want to input experimental data for multiple mutation sequences into the model. In your example, only the format for single mutations is provided:

Variant fitness
WT 1
24K 0.318481518
47A 0.206254044
Could you please provide the format for multiple mutations as well?
